### PR TITLE
Bump yaxpeax arch

### PR DESCRIPTION
**Pull request by novafacing**
Yaxpeax-arch has been recently updated, and the `Decoder` implementation for yaxpeax-riscv is no longer compatible with a current-version yaxpeax-arch.

### CODE REVIEW

**Comment by novafacing** [comment]
Earlier PR accidentally branched from another feature, fixed now and should be mergeable.

**Comment by novafacing** [comment]
@DrChat any opinion on whether this can be merged?

**Comment by DrChat** [comment]
Done!
(A CI workflow would be nice to make this process easier going forward :))

**Comment by novafacing** [comment]
Sure, I can do that 😄 I appreciate it!

**Pull request merged**
